apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-app1
  template:
    metadata:
      labels:
        app: streamlit-app1
    spec:
      containers:
      - name: streamlit-app1
        image: streamlit_app1:latest
        imagePullPolicy: Never   # Local image for Minikube
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service1
spec:
  selector:
    app: streamlit-app1
  ports:
    - protocol: TCP
      port: 80              # External service port
      targetPort: 8501       # Port exposed by the Streamlit app container
  type: NodePort            # Use NodePort for local testing in Minikube

